# For local development only.

services:
  migrations-8.0:
    container_name: migrations-8.0
    hostname: migrations-80
    build: .docker/8.0
    working_dir: /srv
    volumes:
      - .:/srv

  migrations-8.1:
    container_name: migrations-8.1
    hostname: migrations-81
    build: .docker/8.1
    working_dir: /srv
    volumes:
      - .:/srv

  migrations-8.2:
    container_name: migrations-8.2
    hostname: migrations-82
    build: .docker/8.2
    working_dir: /srv
    volumes:
      - .:/srv

  migrations-8.3:
    container_name: migrations-8.3
    hostname: migrations-83
    build: .docker/8.3
    working_dir: /srv
    volumes:
      - .:/srv

  mysql:
    container_name: migrations-mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=phalcon
      - MYSQL_DATABASE=phalcon
      - MYSQL_PASSWORD=secret

  postgres:
    container_name: migrations-postgres
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=phalcon
      - POSTGRES_DB=phalcon
